# Generated by Django 4.1.3 on 2022-11-09 14:02

import main.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_img', models.FileField(max_length=255, upload_to=main.models.upload_vehicle_images)),
                ('back_img', models.FileField(max_length=255, upload_to=main.models.upload_vehicle_images)),
                ('left_side_img', models.FileField(max_length=255, upload_to=main.models.upload_vehicle_images)),
                ('right_side_img', models.FileField(max_length=255, upload_to=main.models.upload_vehicle_images)),
                ('interior_front_img', models.FileField(max_length=255, upload_to=main.models.upload_vehicle_images)),
                ('interior_back_img', models.FileField(max_length=255, upload_to=main.models.upload_vehicle_images)),
                ('boot_img', models.FileField(max_length=255, upload_to=main.models.upload_vehicle_images)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=20)),
                ('top_speed', models.CharField(max_length=8)),
                ('seats', models.IntegerField(max_length=3)),
                ('transmission', models.CharField(max_length=12)),
                ('rates', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plate_no', models.CharField(max_length=7)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle_images')),
            ],
            options={
                'unique_together': {('category', 'plate_no')},
            },
        ),
    ]
