# Generated by Django 4.1.3 on 2022-11-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vehicle_images',
            new_name='VehicleImages',
        ),
    ]
